// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiRouteResponses.Context;

#nullable disable

namespace WebApiRouteResponses.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20241013003733_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApiRouteResponses.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("9bd4c9dd-181f-45e5-8971-2b17ae9a2694"),
                            Active = true,
                            Age = 23,
                            CreationDate = new DateTime(2024, 10, 12, 19, 37, 33, 254, DateTimeKind.Local).AddTicks(7280),
                            LastName = "Julio",
                            Name = "Juan"
                        },
                        new
                        {
                            Id = new Guid("3e918cb1-fb70-44e2-86ce-1120d75d37df"),
                            Active = true,
                            Age = 22,
                            CreationDate = new DateTime(2024, 10, 12, 19, 37, 33, 254, DateTimeKind.Local).AddTicks(7317),
                            LastName = "Vera",
                            Name = "Vero"
                        },
                        new
                        {
                            Id = new Guid("e5bf7599-f991-4a5e-ab0a-1c201eacba33"),
                            Active = true,
                            Age = 23,
                            CreationDate = new DateTime(2024, 10, 12, 19, 37, 33, 254, DateTimeKind.Local).AddTicks(7319),
                            LastName = "Valdiviezo",
                            Name = "Yamileth"
                        });
                });

            modelBuilder.Entity("WebApiRouteResponses.Models.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserRole", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("63cd31a5-68c5-49e7-aef8-dafb48629f79"),
                            Active = true,
                            Role = "Admin",
                            UserId = new Guid("9bd4c9dd-181f-45e5-8971-2b17ae9a2694")
                        },
                        new
                        {
                            Id = new Guid("8746d8f6-6e61-415d-aaa8-49a421ada2b8"),
                            Active = true,
                            Role = "User",
                            UserId = new Guid("3e918cb1-fb70-44e2-86ce-1120d75d37df")
                        },
                        new
                        {
                            Id = new Guid("b82276ff-e75a-4f07-b359-8f167c448e8c"),
                            Active = true,
                            Role = "Support",
                            UserId = new Guid("e5bf7599-f991-4a5e-ab0a-1c201eacba33")
                        });
                });

            modelBuilder.Entity("WebApiRouteResponses.Models.UserRole", b =>
                {
                    b.HasOne("WebApiRouteResponses.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebApiRouteResponses.Models.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
